import type { EventItem } from './types'

export const EVENTS: EventItem[] = [
  {
    id: 'e01',
    infopovod: 'Старт строительства технопарка «Восток-2»',
    speaker: 'Иванов А.С.',
    priority: 'Глава',
    track: 'Трек 1',
    format: 'Выезд',
    department: 'Минэкономики',
    author: 'Андреева М.',
    date: '2026-06-03',
    noExactDate: false,
    goalText: 'Подчеркнуть рост частных инвестиций и новые рабочие места',
  },
  {
    id: 'e02',
    infopovod: 'Открытие нового корпуса перинатального центра',
    speaker: 'Иванов А.С.',
    priority: 'Глава',
    track: 'Трек 2',
    format: 'Пресс-конференция',
    department: 'Минздрав',
    author: 'Белова О.',
    date: '2026-06-05',
    noExactDate: false,
    goalText: 'Демонстрация системного результата по нацпроекту «Здравоохранение»',
  },
  {
    id: 'e03',
    infopovod: 'Прямая линия с жителями',
    speaker: 'Иванов А.С.',
    priority: 'Глава',
    track: 'Отработка рисков',
    format: 'Прямой эфир',
    department: 'Минцифры',
    author: 'Григорьев П.',
    date: '2026-06-12',
    noExactDate: false,
    goalText: 'Снять напряжённость по тарифам ЖКХ и капремонту',
  },
  {
    id: 'e04',
    infopovod: 'Совещание по подготовке к отопительному сезону',
    speaker: 'Петров В.П.',
    priority: 'Премьер и зампреды',
    track: 'Трек 3',
    format: 'Совещание',
    department: 'Минстрой',
    author: 'Дмитриев К.',
    date: '2026-06-09',
    noExactDate: false,
    goalText: 'Зафиксировать готовность сетей и план по ремонтам',
  },
  {
    id: 'e05',
    infopovod: 'Интервью о реализации нацпроекта «Демография»',
    speaker: 'Сидорова Е.К.',
    priority: 'Премьер и зампреды',
    track: 'Нац проект',
    format: 'Интервью',
    department: 'Минсоцполитики',
    author: 'Егорова Л.',
    date: '2026-06-15',
    noExactDate: false,
    goalText: 'Показать результаты мер поддержки семей с детьми',
  },
  {
    id: 'e06',
    infopovod: 'Выезд на объект капремонта школы №12',
    speaker: 'Кузнецов М.Н.',
    priority: 'Премьер и зампреды',
    track: 'Трек 2',
    format: 'Выезд',
    department: 'Минобр',
    author: 'Андреева М.',
    date: '2026-06-18',
    noExactDate: false,
    goalText: 'Фиксация графика готовности к 1 сентября',
  },
  {
    id: 'e07',
    infopovod: 'Брифинг по итогам ПМЭФ',
    speaker: 'Иванов А.С.',
    priority: 'Глава',
    track: 'Трек 1',
    format: 'Брифинг',
    department: 'Минэкономики',
    author: 'Белова О.',
    date: '2026-06-22',
    noExactDate: false,
    goalText: 'Подписанные соглашения, объём инвестиций, новые проекты',
  },
  {
    id: 'e08',
    infopovod: 'Публикация колонки о развитии сельских территорий',
    speaker: 'Морозов О.Д.',
    priority: 'Фон',
    track: 'Трек 1',
    format: 'Публикация',
    department: 'Минсельхоз',
    author: 'Григорьев П.',
    date: '2026-06-25',
    noExactDate: false,
    goalText: 'Положительный фон по теме АПК и господдержки',
  },
  {
    id: 'e09',
    infopovod: 'Реакция на аварию на трассе М-7',
    speaker: 'Петров В.П.',
    priority: 'Премьер и зампреды',
    track: 'Отработка рисков',
    format: 'Брифинг',
    department: 'Минстрой',
    author: 'Дмитриев К.',
    date: '2026-06-04',
    noExactDate: false,
    goalText: 'Чёткая информация по пострадавшим и сроки ремонта',
  },
  {
    id: 'e10',
    infopovod: 'Открытие фестиваля «Голос региона»',
    speaker: 'Сидорова Е.К.',
    priority: 'Фон',
    track: 'Трек 2',
    format: 'Выезд',
    department: 'Минкульт',
    author: 'Егорова Л.',
    date: '2026-06-28',
    noExactDate: false,
    goalText: 'Тёплый человечный фон, поддержка культурной повестки',
  },
  {
    id: 'e11',
    infopovod: 'Совещание по цифровизации госуслуг',
    speaker: 'Кузнецов М.Н.',
    priority: 'Премьер и зампреды',
    track: 'Нац проект',
    format: 'Совещание',
    department: 'Минцифры',
    author: 'Андреева М.',
    date: '2026-06-11',
    noExactDate: false,
    goalText: 'Прогресс по показателям нацпроекта «Цифровая экономика»',
  },
  {
    id: 'e12',
    infopovod: 'Интервью федеральному изданию о промышленности',
    speaker: 'Иванов А.С.',
    priority: 'Глава',
    track: 'Трек 1',
    format: 'Интервью',
    department: 'Минэкономики',
    author: 'Белова О.',
    date: '',
    noExactDate: true,
    goalText: 'Закрепить статус региона как промышленного центра',
  },
  {
    id: 'e13',
    infopovod: 'Объезд социальных объектов',
    speaker: 'Сидорова Е.К.',
    priority: 'Премьер и зампреды',
    track: 'Трек 2',
    format: 'Выезд',
    department: 'Минсоцполитики',
    author: 'Дмитриев К.',
    date: '2026-07-02',
    noExactDate: false,
    goalText: 'Контроль исполнения соцобязательств в районах',
  },
  {
    id: 'e14',
    infopovod: 'Публикация в Telegram о благоустройстве дворов',
    speaker: 'Морозов О.Д.',
    priority: 'Фон',
    track: 'Трек 3',
    format: 'Публикация',
    department: 'Минстрой',
    author: 'Григорьев П.',
    date: '2026-07-04',
    noExactDate: false,
    goalText: 'Локальный позитивный охват',
  },
  {
    id: 'e15',
    infopovod: 'Пресс-конференция по итогам полугодия',
    speaker: 'Иванов А.С.',
    priority: 'Глава',
    track: 'Трек 1',
    format: 'Пресс-конференция',
    department: 'Минэкономики',
    author: 'Егорова Л.',
    date: '2026-07-10',
    noExactDate: false,
    goalText: 'Главные цифры и приоритеты второго полугодия',
  },
  {
    id: 'e16',
    infopovod: 'Прямой эфир «Час с министром» — образование',
    speaker: 'Кузнецов М.Н.',
    priority: 'Премьер и зампреды',
    track: 'Трек 2',
    format: 'Прямой эфир',
    department: 'Минобр',
    author: 'Андреева М.',
    date: '2026-07-15',
    noExactDate: false,
    goalText: 'Ответы на вопросы родителей по ЕГЭ и приёмной кампании',
  },
  {
    id: 'e17',
    infopovod: 'Совещание по паводковой обстановке',
    speaker: 'Петров В.П.',
    priority: 'Премьер и зампреды',
    track: 'Отработка рисков',
    format: 'Совещание',
    department: 'Минстрой',
    author: 'Белова О.',
    date: '',
    noExactDate: true,
    goalText: 'Готовность сил и средств, оповещение населения',
  },
  {
    id: 'e18',
    infopovod: 'Выезд на молочный комплекс «Заря»',
    speaker: 'Морозов О.Д.',
    priority: 'Фон',
    track: 'Нац проект',
    format: 'Выезд',
    department: 'Минсельхоз',
    author: 'Дмитриев К.',
    date: '2026-07-21',
    noExactDate: false,
    goalText: 'Показать результаты нацпроекта «МСП»',
  },
  {
    id: 'e19',
    infopovod: 'Публикация рейтинга по нацпроектам',
    speaker: 'Сидорова Е.К.',
    priority: 'Фон',
    track: 'Нац проект',
    format: 'Публикация',
    department: 'Минэкономики',
    author: 'Григорьев П.',
    date: '2026-07-25',
    noExactDate: false,
    goalText: 'Региональное место среди субъектов',
  },
  {
    id: 'e20',
    infopovod: 'Интервью о подготовке к учебному году',
    speaker: 'Кузнецов М.Н.',
    priority: 'Премьер и зампреды',
    track: 'Трек 2',
    format: 'Интервью',
    department: 'Минобр',
    author: 'Егорова Л.',
    date: '2026-08-05',
    noExactDate: false,
    goalText: 'Уверенность родителей в готовности школ',
  },
  {
    id: 'e21',
    infopovod: 'Брифинг по тарифам ЖКХ',
    speaker: 'Петров В.П.',
    priority: 'Премьер и зампреды',
    track: 'Отработка рисков',
    format: 'Брифинг',
    department: 'Минстрой',
    author: 'Андреева М.',
    date: '2026-08-12',
    noExactDate: false,
    goalText: 'Прозрачность изменений и адресные меры поддержки',
  },
  {
    id: 'e22',
    infopovod: 'Открытие нового ФАПа в Кезском районе',
    speaker: 'Иванов А.С.',
    priority: 'Глава',
    track: 'Нац проект',
    format: 'Выезд',
    department: 'Минздрав',
    author: 'Белова О.',
    date: '2026-08-18',
    noExactDate: false,
    goalText: 'Доступность медпомощи в сельской местности',
  },
]
